[package]
name = "rustylogger"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.37"
serde_json = "1.0.115"
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
smallvec = "1.13.2"
